"use client";

import { useEffect, useState, useTransition } from "react";
import { updateUnitProduct } from "../actions";
import { Input } from "@/components/ui/input";

interface Props {
    item: any;
    index: number;
    onDelete: (id: number | string) => void;
    isDeleting?: boolean;
    isSelected: boolean;
    onSelectToggle: (id: number | string) => void;
}

export function DbTableRow({ item, index, onDelete, isDeleting = false, isSelected, onSelectToggle }: Props) {
    const [isEditing, setIsEditing] = useState(false);
    const [isPending, startTransition] = useTransition();

    const formattedDbNumber = String(item.production_number || 0).padStart(4, "0");

    const [formValues, setFormValues] = useState({
        batch: item.batch ?? "",
        production_code: item.production_code ?? "",
        spk: item.spk ?? "",
        remarks: item.remarks ?? "",
        out_date: item.out_code_date ? new Date(item.out_code_date).toISOString().split("T")[0] : "",
        recipient: item.item_code_recipient,
    });

    useEffect(() => {
        setFormValues({
            batch: item.batch ?? "",
            production_code: item.production_code ?? "",
            spk: item.spk ?? "",
            remarks: item.remarks ?? "",
            out_date: item.out_code_date ? new Date(item.out_code_date).toISOString().split("T")[0] : "",
            recipient: item.item_code_recipient,
        });
    }, [item]);

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const { name, value } = e.target;

        setFormValues((prev) => {
            if (name === "batch") {
                const productCode = item.product_code?.product_code ?? "";
                const autoGeneratedCode = value
                    ? `${productCode}-${value}${formattedDbNumber}`
                    : item.production_code;

                return {
                    ...prev,
                    batch: value,
                    production_code: autoGeneratedCode,
                };
            }

            return {
                ...prev,
                [name]: value,
            };
        });
    };

    const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        const formData = new FormData(e.currentTarget);

        startTransition(async () => {
            const res = await updateUnitProduct(null, formData);
            if (res?.success) {
                setIsEditing(false);
            } else if (res?.message) {
                alert(res.message);
            }
        });
    };

    if (isEditing) {
        return (
            <tr className="bg-blue-50/70 border-y-2 border-blue-400 transition-all">
                <td className="px-4 py-3 text-center">
                    <input
                        type="checkbox"
                        checked={isSelected}
                        onChange={() => onSelectToggle(item.id)}
                        className="w-4 h-4 rounded text-[#0E5EA2] focus:ring-[#0E5EA2] cursor-pointer"
                    />
                </td>
                <td className="px-3 py-2 text-center text-gray-500">{index + 1}</td>
                <td className="px-3 py-2 font-medium">{item.product?.product_name}</td>
                <td className="px-3 py-2">{item.product?.product_type}</td>
                <td className="px-3 py-2">{item.product_code?.product_code}</td>

                <td className="px-3 py-2">
                    <Input
                        form={`edit-form-${item.id}`}
                        name="batch"
                        value={formValues.batch}
                        onChange={handleInputChange}
                        className="h-8 text-xs bg-white min-w-[90px]"
                    />
                </td>

                <td className="px-3 py-2 font-mono">{formattedDbNumber}</td>

                <td className="px-3 py-2 font-mono font-bold text-[#0E5EA2]">
                    <Input
                        form={`edit-form-${item.id}`}
                        name="production_code"
                        value={formValues.production_code}
                        onChange={handleInputChange}
                        className="h-8 text-xs bg-white min-w-[140px]"
                        readOnly
                    />
                </td>

                <td className="px-3 py-2">{item.customer?.name}</td>

                <td className="px-3 py-2">
                    <Input
                        form={`edit-form-${item.id}`}
                        name="spk"
                        value={formValues.spk}
                        onChange={handleInputChange}
                        className="h-8 text-xs bg-white min-w-[90px]"
                    />
                </td>

                <td className="px-3 py-2">
                    <Input
                        form={`edit-form-${item.id}`}
                        name="remarks"
                        value={formValues.remarks}
                        onChange={handleInputChange}
                        className="h-8 text-xs bg-white min-w-[120px]"
                    />
                </td>

                <td className="px-3 py-2">
                    <Input
                        form={`edit-form-${item.id}`}
                        type="date"
                        name="out_date"
                        value={formValues.out_date}
                        onChange={handleInputChange}
                        className="h-8 text-xs bg-white w-[130px]"
                    />
                </td>

                <td className="px-3 py-2">
                    <Input
                        form={`edit-form-${item.id}`}
                        name="recipient"
                        value={formValues.recipient}
                        onChange={handleInputChange}
                        className="h-8 text-xs bg-white min-w-[100px]"
                    />
                </td>

                <td className="px-3 py-2 text-center">
                    <span className="inline-block px-2 py-0.5 text-xs font-semibold bg-amber-100 text-amber-800 rounded-full">
                        Editing...
                    </span>
                </td>

                <td className="px-3 py-2 text-center">
                    <form id={`edit-form-${item.id}`} onSubmit={handleSubmit}>
                        <input type="hidden" name="id" value={item.id} />
                    </form>
                    <div className="inline-flex items-center gap-1.5">
                        <button
                            type="submit"
                            form={`edit-form-${item.id}`}
                            disabled={isPending}
                            className="text-xs font-semibold bg-emerald-600 text-white px-2 py-1 rounded hover:bg-emerald-700 disabled:bg-emerald-300 transition"
                        >
                            {isPending ? "..." : "Simpan"}
                        </button>
                        <button
                            type="button"
                            onClick={() => setIsEditing(false)}
                            disabled={isPending}
                            className="text-xs font-medium bg-slate-200 text-slate-700 px-2 py-1 rounded hover:bg-slate-300 transition"
                        >
                            Batal
                        </button>
                    </div>
                </td>
            </tr>
        );
    }

    return (
        <tr className={`hover:bg-blue-50/50 transition-colors ${isDeleting ? "opacity-40 pointer-events-none bg-red-50" : ""}`}>
            <td className="px-4 py-3 text-center">
                <input
                    type="checkbox"
                    checked={isSelected}
                    onChange={() => onSelectToggle(item.id)}
                    className="w-4 h-4 rounded text-[#0E5EA2] focus:ring-[#0E5EA2] cursor-pointer"
                />
            </td>
            <td className="px-4 py-3 text-center text-gray-500">{index + 1}</td>
            <td className="px-4 py-3 font-medium">{item.product?.product_name}</td>
            <td className="px-4 py-3">{item.product?.product_type}</td>
            <td className="px-4 py-3">{item.product_code?.product_code}</td>
            <td className="px-4 py-3 font-mono">{item.batch || "-"}</td>
            <td className="px-4 py-3 font-mono">{formattedDbNumber}</td>
            <td className="px-4 py-3 font-mono font-bold text-[#0E5EA2]">{item.production_code}</td>
            <td className="px-4 py-3">{item.customer?.name}</td>
            <td className="px-4 py-3">{item.spk || "-"}</td>
            <td className="px-4 py-3">{item.remarks || "-"}</td>
            <td className="px-4 py-3">
                {item.out_code_date ? new Date(item.out_code_date).toLocaleDateString("id-ID") : "-"}
            </td>
            <td className="px-4 py-3">{item.item_code_recipient}</td>

            <td className="px-4 py-3 text-center">
                <span className="inline-block px-2.5 py-1 text-xs font-semibold bg-emerald-100 text-emerald-800 rounded-full">
                    {item.status ?? "Tersimpan"}
                </span>
            </td>

            <td className="px-4 py-3 text-center">
                <div className="inline-flex items-center gap-2">
                    <button
                        type="button"
                        onClick={() => setIsEditing(true)}
                        disabled={isDeleting}
                        className="text-xs font-medium text-blue-600 hover:text-blue-800 hover:underline transition disabled:text-gray-300"
                    >
                        Edit
                    </button>
                    <span className="text-slate-300">|</span>
                    <button
                        type="button"
                        onClick={() => onDelete(item.id)}
                        disabled={isDeleting}
                        className="text-xs font-medium text-red-600 hover:text-red-800 hover:underline transition disabled:text-gray-400"
                    >
                        {isDeleting ? "Menghapus..." : "Hapus"}
                    </button>
                </div>
            </td>
        </tr>
    );
}