"use client";

import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { DraftItem } from "@/components/production-codes/types";

interface Props {
    draft: DraftItem;
    formAction: (payload: FormData) => void;
    onDraftChange: (
        tempId: string,
        field: keyof DraftItem,
        value: string | number | boolean
    ) => void;
    onRemoveDraft: (tempId: string) => void;
    onSubmitStart: (tempId: string) => void;
    onDuplicateDraft: (draft: DraftItem) => void; // <-- 1. Tambahkan prop ini
}

export function DraftTableRow({
    draft,
    formAction,
    onDraftChange,
    onRemoveDraft,
    onSubmitStart,
    onDuplicateDraft, // <-- 2. Terima prop di sini
}: Props) {
    const formattedProductionNumber = String(draft.productionNumber).padStart(4, "0");
    const autoGeneratedCode = `${draft.productCode}-${draft.batch ?? ""}${formattedProductionNumber}`;

    return (
        <tr className="bg-amber-50/80 border-b-2 border-amber-300">
            <td className="px-4 py-3 text-center font-bold text-amber-700">npm</td>
            <td className="px-4 py-3 text-center font-bold text-amber-700">Draft</td>
            <td className="px-4 py-3 font-medium">{draft.productName}</td>
            <td className="px-4 py-3">{draft.productType}</td>
            <td className="px-4 py-3">{draft.productCode}</td>

            <td className="px-2 py-2">
                <Input
                    type="text"
                    placeholder="Batch (e.g. VI26)..."
                    value={draft.batch}
                    onChange={(e) => onDraftChange(draft.tempId, "batch", e.target.value)}
                    className="h-8 text-xs bg-white font-mono min-w-[100px]"
                />
            </td>

            <td className="px-4 py-3 font-semibold text-amber-900 font-mono">
                {formattedProductionNumber}
            </td>
            <td className="px-4 py-3 font-mono text-xs text-amber-800 font-bold">
                {autoGeneratedCode}
            </td>
            <td className="px-4 py-3">{draft.customerName}</td>

            <td className="px-2 py-2">
                <Input
                    type="text"
                    placeholder="SPK..."
                    value={draft.spk}
                    onChange={(e) => onDraftChange(draft.tempId, "spk", e.target.value)}
                    className="h-8 text-xs bg-white min-w-[90px]"
                />
            </td>

            <td className="px-2 py-2">
                <Input
                    type="text"
                    placeholder="Keterangan..."
                    value={draft.remarks}
                    onChange={(e) => onDraftChange(draft.tempId, "remarks", e.target.value)}
                    className="h-8 text-xs bg-white min-w-[120px]"
                />
            </td>

            <td className="px-2 py-2">
                <Input
                    type="date"
                    value={draft.outDate}
                    onChange={(e) => onDraftChange(draft.tempId, "outDate", e.target.value)}
                    className="h-8 text-xs bg-white w-36"
                />
            </td>

            <td className="px-2 py-2">
                <Input
                    type="text"
                    placeholder="Penerima..."
                    value={draft.recipient}
                    onChange={(e) => onDraftChange(draft.tempId, "recipient", e.target.value)}
                    className="h-8 text-xs bg-white min-w-[100px]"
                />
            </td>

            <td className="px-4 py-3 text-center">
                <Badge variant="outline" className="bg-amber-100 text-amber-800 border-amber-300">
                    Draft
                </Badge>
            </td>

            <td className="px-4 py-3 text-center">
                <form
                    action={formAction}
                    onSubmit={() => onSubmitStart(draft.tempId)}
                    className="inline-flex gap-1"
                >
                    <input type="hidden" name="product_id" value={draft.productId} />
                    <input type="hidden" name="product_code_id" value={draft.productCodeId} />
                    <input type="hidden" name="customer_id" value={draft.customerId} />
                    <input type="hidden" name="production_number" value={draft.productionNumber} />
                    <input type="hidden" name="production_code" value={autoGeneratedCode} />
                    <input type="hidden" name="batch" value={draft.batch} />
                    <input type="hidden" name="spk" value={draft.spk} />
                    <input type="hidden" name="remarks" value={draft.remarks} />
                    <input type="hidden" name="out_date" value={draft.outDate} />
                    <input type="hidden" name="recipient" value={draft.recipient} />

                    <Button
                        type="submit"
                        size="sm"
                        className="h-7 text-xs bg-emerald-600 hover:bg-emerald-700 text-white px-2.5"
                    >
                        Simpan
                    </Button>

                    {/* 3. Tombol Duplikat Baru */}
                    <Button
                        type="button"
                        size="sm"
                        onClick={() => onDuplicateDraft(draft)}
                        className="h-7 text-xs bg-amber-600 hover:bg-amber-700 text-white px-2.5"
                    >
                        Duplikat
                    </Button>

                    <Button
                        type="button"
                        variant="destructive"
                        size="sm"
                        onClick={() => onRemoveDraft(draft.tempId)}
                        className="h-7 text-xs px-2.5"
                    >
                        Batal
                    </Button>
                </form>
            </td>
        </tr>
    );
}